name: eco_track1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # NEW DEPENDENCIES ADDED BELOW (all existing content preserved exactly)
  syncfusion_flutter_charts: ^24.1.47
  smooth_page_indicator: ^1.1.0
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  mobile_scanner: ^3.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Added assets section (keeping all your existing comments)
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/auth/
    - assets/images/products/
    - assets/images/brands/
    - assets/images/icons/
    - assets/images/misc/